- name: Setup Python version
  uses: actions/setup-python@v5
  with:
    python-version: ${{ env.PYTHON_VERSION }}

- name: Install dependencies
  run: |
    pip install -r requirements.txt \
      --target=".python_packages/lib/site-packages"

- name: Zip artifact for deployment
  run: |
    zip -r release.zip . \
      -x "venv/*" \
      -x ".git/*"
